namespace Otanabi.Extensions.Models.Doramasflix;
public static class RequestQueries
{
    public const string latestUpdatesQuery = "{\"operationName\":\"listDoramas\",\"variables\":{\"page\":{0},\"sort\":\"CREATEDAT_DESC\",\"perPage\":35,\"filter\":{\"isTVShow\":false}},\"query\":\"query listDoramas($page: Int, $perPage: Int, $sort: SortFindManyDoramaInput, $filter: FilterFindManyDoramaInput) {\\n  paginationDorama(page: $page, perPage: $perPage, sort: $sort, filter: $filter) {\\n    count\\n    pageInfo {\\n      currentPage\\n      hasNextPage\\n      hasPreviousPage\\n      __typename\\n    }\\n    items {\\n      _id\\n      name\\n      name_es\\n      slug\\n      cast\\n      names\\n      overview\\n      languages\\n      created_by\\n      popularity\\n      poster_path\\n      vote_average\\n      backdrop_path\\n      first_air_date\\n      episode_run_time\\n      isTVShow\\n      poster\\n      backdrop\\n      genres {\\n        name\\n        slug\\n        __typename\\n      }\\n      networks {\\n        name\\n        slug\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\"}";
    public const string episodesQuery = "{\"operationName\":\"listEpisodes\",\"variables\":{\"serie_id\":\"{0}\",\"season_number\":{1}},\"query\":\"query listEpisodes($season_number: Float!, $serie_id: MongoID!) {\\n  listEpisodes(sort: NUMBER_ASC, filter: {type_serie: \\\"dorama\\\", serie_id: $serie_id, season_number: $season_number}) {\\n    _id\\n    name\\n    slug\\n    serie_name\\n    serie_name_es\\n    serie_id\\n    still_path\\n    air_date\\n    season_number\\n    episode_number\\n    languages\\n    poster\\n    backdrop\\n    __typename\\n  }\\n}\\n\"}";
    public const string seasonsQuery = "{\"operationName\":\"listSeasons\",\"variables\":{\"serie_id\":\"{0}\"},\"query\":\"query listSeasons($serie_id: MongoID!) {\\n  listSeasons(sort: NUMBER_ASC, filter: {serie_id: $serie_id}) {\\n    slug\\n    season_number\\n    poster_path\\n    air_date\\n    serie_name\\n    poster\\n    backdrop\\n    __typename\\n  }\\n}\\n\"}";
    public const string searchQuery = "{\"operationName\":\"searchAll\",\"variables\":{\"input\":\"{0}\"},\"query\":\"query searchAll($input: String!) {\\n  searchDorama(input: $input, limit: 35) {\\n    _id\\n    slug\\n    name\\n    name_es\\n    poster_path\\n    poster\\n    __typename\\n  }\\n  searchMovie(input: $input, limit: 35) {\\n    _id\\n    name\\n    name_es\\n    slug\\n    poster_path\\n    poster\\n    __typename\\n  }\\n}\\n\"}";
    public const string moviesQuery = "{\"operationName\":\"listMovies\",\"variables\":{\"perPage\":35,\"sort\":\"CREATEDAT_DESC\",\"filter\":{},\"page\":{0}},\"query\":\"query listMovies($page: Int, $perPage: Int, $sort: SortFindManyMovieInput, $filter: FilterFindManyMovieInput) {\\n  paginationMovie(page: $page, perPage: $perPage, sort: $sort, filter: $filter) {\\n    count\\n    pageInfo {\\n      currentPage\\n      hasNextPage\\n      hasPreviousPage\\n      __typename\\n    }\\n    items {\\n      _id\\n      name\\n      name_es\\n      slug\\n      cast\\n      names\\n      overview\\n      languages\\n      popularity\\n      poster_path\\n      vote_average\\n      backdrop_path\\n      release_date\\n      runtime\\n      poster\\n      backdrop\\n      genres {\\n        name\\n        __typename\\n      }\\n      networks {\\n        name\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\"}";
    public const string varietiesQuery = "{\"operationName\":\"listDoramas\",\"variables\":{\"page\":{0},\"sort\":\"CREATEDAT_DESC\",\"perPage\":35,\"filter\":{\"isTVShow\":true}},\"query\":\"query listDoramas($page: Int, $perPage: Int, $sort: SortFindManyDoramaInput, $filter: FilterFindManyDoramaInput) {\\n  paginationDorama(page: $page, perPage: $perPage, sort: $sort, filter: $filter) {\\n    count\\n    pageInfo {\\n      currentPage\\n      hasNextPage\\n      hasPreviousPage\\n      __typename\\n    }\\n    items {\\n      _id\\n      name\\n      name_es\\n      slug\\n      cast\\n      names\\n      overview\\n      languages\\n      created_by\\n      popularity\\n      poster_path\\n      vote_average\\n      backdrop_path\\n      first_air_date\\n      episode_run_time\\n      isTVShow\\n      poster\\n      backdrop\\n      genres {\\n        name\\n        slug\\n        __typename\\n      }\\n      networks {\\n        name\\n        slug\\n        __typename\\n      }\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\"}";
    public const string searchByGenreQuery = "{\"operationName\": \"listDoramas\",\"variables\": {\"limit\": 50,\"skip\": 0,\"filter\": {\"genres\": [{\"slug\": \"{0}\"}]}},\"query\": \"query listDoramas($limit: Int, $skip: Int, $sort: SortFindManyDoramaInput, $filter: FilterFindManyDoramaInput) { listDoramas(limit: $limit, skip: $skip, sort: $sort, filter: $filter) { _id name name_es slug cast names overview languages created_by popularity poster_path vote_average backdrop_path first_air_date episode_run_time isTVShow poster backdrop genres {   name   slug   __typename } networks {   name   slug   __typename } __typename } }\"}";
}